/*
 * arch/arm/mach-tegra/include/mach/tegra2_fuse.h
 *
 * Copyright (c) 2010, NVIDIA Corporation.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#ifndef __MACH_TEGRA2_FUSE_H
#define __MACH_TEGRA2_FUSE_H

#define FUSE_ENABLE_PROGRAM_WIDTH 1
#define FUSE_ENABLE_PROGRAM_PRI_0 0x0
#define FUSE_ENABLE_PROGRAM_PRI_0_DATA 0:0
#define FUSE_ENABLE_PROGRAM_PRI_0_WIDTH 1
#define FUSE_ENABLE_PROGRAM_RED_0 0x1
#define FUSE_ENABLE_PROGRAM_RED_0_DATA 0:0
#define FUSE_ENABLE_PROGRAM_RED_0_WIDTH 1

#define FUSE_SECURITY_MODE_WIDTH 1
#define FUSE_SECURITY_MODE_PRI_0 0x0
#define FUSE_SECURITY_MODE_PRI_0_DATA 23:23
#define FUSE_SECURITY_MODE_PRI_0_WIDTH 1
#define FUSE_SECURITY_MODE_RED_0 0x1
#define FUSE_SECURITY_MODE_RED_0_DATA 23:23
#define FUSE_SECURITY_MODE_RED_0_WIDTH 1

#define FUSE_ARM_DEBUG_DIS_WIDTH 1
#define FUSE_ARM_DEBUG_DIS_PRI_0 0x0
#define FUSE_ARM_DEBUG_DIS_PRI_0_DATA 24:24
#define FUSE_ARM_DEBUG_DIS_PRI_0_WIDTH 1
#define FUSE_ARM_DEBUG_DIS_RED_0 0x1
#define FUSE_ARM_DEBUG_DIS_RED_0_DATA 24:24
#define FUSE_ARM_DEBUG_DIS_RED_0_WIDTH 1

#define FUSE_PRIVATE_KEY0_WIDTH 32
#define FUSE_PRIVATE_KEY0_PRI_0 0xa
#define FUSE_PRIVATE_KEY0_PRI_0_DATA 31:8
#define FUSE_PRIVATE_KEY0_PRI_0_WIDTH 24
#define FUSE_PRIVATE_KEY0_PRI_1 0xc
#define FUSE_PRIVATE_KEY0_PRI_1_DATA 7:0
#define FUSE_PRIVATE_KEY0_PRI_1_WIDTH 8
#define FUSE_PRIVATE_KEY0_RED_0 0xb
#define FUSE_PRIVATE_KEY0_RED_0_DATA 31:8
#define FUSE_PRIVATE_KEY0_RED_0_WIDTH 24
#define FUSE_PRIVATE_KEY0_RED_1 0xd
#define FUSE_PRIVATE_KEY0_RED_1_DATA 7:0
#define FUSE_PRIVATE_KEY0_RED_1_WIDTH 8

#define FUSE_PRIVATE_KEY1_WIDTH 32
#define FUSE_PRIVATE_KEY1_PRI_0 0xc
#define FUSE_PRIVATE_KEY1_PRI_0_DATA 31:8
#define FUSE_PRIVATE_KEY1_PRI_0_WIDTH 24
#define FUSE_PRIVATE_KEY1_PRI_1 0xe
#define FUSE_PRIVATE_KEY1_PRI_1_DATA 7:0
#define FUSE_PRIVATE_KEY1_PRI_1_WIDTH 8
#define FUSE_PRIVATE_KEY1_RED_0 0xd
#define FUSE_PRIVATE_KEY1_RED_0_DATA 31:8
#define FUSE_PRIVATE_KEY1_RED_0_WIDTH 24
#define FUSE_PRIVATE_KEY1_RED_1 0xf
#define FUSE_PRIVATE_KEY1_RED_1_DATA 7:0
#define FUSE_PRIVATE_KEY1_RED_1_WIDTH 8

#define FUSE_PRIVATE_KEY2_WIDTH 32
#define FUSE_PRIVATE_KEY2_PRI_0 0xe
#define FUSE_PRIVATE_KEY2_PRI_0_DATA 31:8
#define FUSE_PRIVATE_KEY2_PRI_0_WIDTH 24
#define FUSE_PRIVATE_KEY2_PRI_1 0x10
#define FUSE_PRIVATE_KEY2_PRI_1_DATA 7:0
#define FUSE_PRIVATE_KEY2_PRI_1_WIDTH 8
#define FUSE_PRIVATE_KEY2_RED_0 0xf
#define FUSE_PRIVATE_KEY2_RED_0_DATA 31:8
#define FUSE_PRIVATE_KEY2_RED_0_WIDTH 24
#define FUSE_PRIVATE_KEY2_RED_1 0x11
#define FUSE_PRIVATE_KEY2_RED_1_DATA 7:0
#define FUSE_PRIVATE_KEY2_RED_1_WIDTH 8

#define FUSE_PRIVATE_KEY3_WIDTH 32
#define FUSE_PRIVATE_KEY3_PRI_0 0x10
#define FUSE_PRIVATE_KEY3_PRI_0_DATA 31:8
#define FUSE_PRIVATE_KEY3_PRI_0_WIDTH 24
#define FUSE_PRIVATE_KEY3_PRI_1 0x12
#define FUSE_PRIVATE_KEY3_PRI_1_DATA 7:0
#define FUSE_PRIVATE_KEY3_PRI_1_WIDTH 8
#define FUSE_PRIVATE_KEY3_RED_0 0x11
#define FUSE_PRIVATE_KEY3_RED_0_DATA 31:8
#define FUSE_PRIVATE_KEY3_RED_0_WIDTH 24
#define FUSE_PRIVATE_KEY3_RED_1 0x13
#define FUSE_PRIVATE_KEY3_RED_1_DATA 7:0
#define FUSE_PRIVATE_KEY3_RED_1_WIDTH 8

#define FUSE_PRIVATE_KEY4_WIDTH 32
#define FUSE_PRIVATE_KEY4_PRI_0 0x12
#define FUSE_PRIVATE_KEY4_PRI_0_DATA 31:8
#define FUSE_PRIVATE_KEY4_PRI_0_WIDTH 24
#define FUSE_PRIVATE_KEY4_PRI_1 0x14
#define FUSE_PRIVATE_KEY4_PRI_1_DATA 7:0
#define FUSE_PRIVATE_KEY4_PRI_1_WIDTH 8
#define FUSE_PRIVATE_KEY4_RED_0 0x13
#define FUSE_PRIVATE_KEY4_RED_0_DATA 31:8
#define FUSE_PRIVATE_KEY4_RED_0_WIDTH 24
#define FUSE_PRIVATE_KEY4_RED_1 0x15
#define FUSE_PRIVATE_KEY4_RED_1_DATA 7:0
#define FUSE_PRIVATE_KEY4_RED_1_WIDTH 8

#define FUSE_BOOT_DEVICE_INFO_WIDTH 16
#define FUSE_BOOT_DEVICE_INFO_PRI_0 0x14
#define FUSE_BOOT_DEVICE_INFO_PRI_0_DATA 23:8
#define FUSE_BOOT_DEVICE_INFO_PRI_0_WIDTH 16
#define FUSE_BOOT_DEVICE_INFO_RED_0 0x15
#define FUSE_BOOT_DEVICE_INFO_RED_0_DATA 23:8
#define FUSE_BOOT_DEVICE_INFO_RED_0_WIDTH 16

#define FUSE_RESERVED_SW_WIDTH 8
#define FUSE_RESERVED_SW_PRI_0 0x14
#define FUSE_RESERVED_SW_PRI_0_DATA 31:24
#define FUSE_RESERVED_SW_PRI_0_WIDTH 8
#define FUSE_RESERVED_SW_RED_0 0x15
#define FUSE_RESERVED_SW_RED_0_DATA 31:24
#define FUSE_RESERVED_SW_RED_0_WIDTH 8

#define FUSE_RESERVED_ODM0_WIDTH 32
#define FUSE_RESERVED_ODM0_PRI_0 0x16
#define FUSE_RESERVED_ODM0_PRI_0_DATA 31:4
#define FUSE_RESERVED_ODM0_PRI_0_WIDTH 28
#define FUSE_RESERVED_ODM0_PRI_1 0x18
#define FUSE_RESERVED_ODM0_PRI_1_DATA 3:0
#define FUSE_RESERVED_ODM0_PRI_1_WIDTH 4
#define FUSE_RESERVED_ODM0_RED_0 0x17
#define FUSE_RESERVED_ODM0_RED_0_DATA 31:4
#define FUSE_RESERVED_ODM0_RED_0_WIDTH 28
#define FUSE_RESERVED_ODM0_RED_1 0x19
#define FUSE_RESERVED_ODM0_RED_1_DATA 3:0
#define FUSE_RESERVED_ODM0_RED_1_WIDTH 4

#define FUSE_RESERVED_ODM1_WIDTH 32
#define FUSE_RESERVED_ODM1_PRI_0 0x18
#define FUSE_RESERVED_ODM1_PRI_0_DATA 31:4
#define FUSE_RESERVED_ODM1_PRI_0_WIDTH 28
#define FUSE_RESERVED_ODM1_PRI_1 0x1a
#define FUSE_RESERVED_ODM1_PRI_1_DATA 3:0
#define FUSE_RESERVED_ODM1_PRI_1_WIDTH 4
#define FUSE_RESERVED_ODM1_RED_0 0x19
#define FUSE_RESERVED_ODM1_RED_0_DATA 31:4
#define FUSE_RESERVED_ODM1_RED_0_WIDTH 28
#define FUSE_RESERVED_ODM1_RED_1 0x1b
#define FUSE_RESERVED_ODM1_RED_1_DATA 3:0
#define FUSE_RESERVED_ODM1_RED_1_WIDTH 4

#define FUSE_RESERVED_ODM2_WIDTH 32
#define FUSE_RESERVED_ODM2_PRI_0 0x1a
#define FUSE_RESERVED_ODM2_PRI_0_DATA 31:4
#define FUSE_RESERVED_ODM2_PRI_0_WIDTH 28
#define FUSE_RESERVED_ODM2_PRI_1 0x1c
#define FUSE_RESERVED_ODM2_PRI_1_DATA 3:0
#define FUSE_RESERVED_ODM2_PRI_1_WIDTH 4
#define FUSE_RESERVED_ODM2_RED_0 0x1b
#define FUSE_RESERVED_ODM2_RED_0_DATA 31:4
#define FUSE_RESERVED_ODM2_RED_0_WIDTH 28
#define FUSE_RESERVED_ODM2_RED_1 0x1d
#define FUSE_RESERVED_ODM2_RED_1_DATA 3:0
#define FUSE_RESERVED_ODM2_RED_1_WIDTH 4

#define FUSE_RESERVED_ODM3_WIDTH 32
#define FUSE_RESERVED_ODM3_PRI_0 0x1c
#define FUSE_RESERVED_ODM3_PRI_0_DATA 31:4
#define FUSE_RESERVED_ODM3_PRI_0_WIDTH 28
#define FUSE_RESERVED_ODM3_PRI_1 0x1e
#define FUSE_RESERVED_ODM3_PRI_1_DATA 3:0
#define FUSE_RESERVED_ODM3_PRI_1_WIDTH 4
#define FUSE_RESERVED_ODM3_RED_0 0x1d
#define FUSE_RESERVED_ODM3_RED_0_DATA 31:4
#define FUSE_RESERVED_ODM3_RED_0_WIDTH 28
#define FUSE_RESERVED_ODM3_RED_1 0x1f
#define FUSE_RESERVED_ODM3_RED_1_DATA 3:0
#define FUSE_RESERVED_ODM3_RED_1_WIDTH 4

#define FUSE_RESERVED_ODM4_WIDTH 32
#define FUSE_RESERVED_ODM4_PRI_0 0x1e
#define FUSE_RESERVED_ODM4_PRI_0_DATA 31:4
#define FUSE_RESERVED_ODM4_PRI_0_WIDTH 28
#define FUSE_RESERVED_ODM4_PRI_1 0x20
#define FUSE_RESERVED_ODM4_PRI_1_DATA 3:0
#define FUSE_RESERVED_ODM4_PRI_1_WIDTH 4
#define FUSE_RESERVED_ODM4_RED_0 0x1f
#define FUSE_RESERVED_ODM4_RED_0_DATA 31:4
#define FUSE_RESERVED_ODM4_RED_0_WIDTH 28
#define FUSE_RESERVED_ODM4_RED_1 0x21
#define FUSE_RESERVED_ODM4_RED_1_DATA 3:0
#define FUSE_RESERVED_ODM4_RED_1_WIDTH 4

#define FUSE_RESERVED_ODM5_WIDTH 32
#define FUSE_RESERVED_ODM5_PRI_0 0x20
#define FUSE_RESERVED_ODM5_PRI_0_DATA 31:4
#define FUSE_RESERVED_ODM5_PRI_0_WIDTH 28
#define FUSE_RESERVED_ODM5_PRI_1 0x22
#define FUSE_RESERVED_ODM5_PRI_1_DATA 3:0
#define FUSE_RESERVED_ODM5_PRI_1_WIDTH 4
#define FUSE_RESERVED_ODM5_RED_0 0x21
#define FUSE_RESERVED_ODM5_RED_0_DATA 31:4
#define FUSE_RESERVED_ODM5_RED_0_WIDTH 28
#define FUSE_RESERVED_ODM5_RED_1 0x23
#define FUSE_RESERVED_ODM5_RED_1_DATA 3:0
#define FUSE_RESERVED_ODM5_RED_1_WIDTH 4

#define FUSE_RESERVED_ODM6_WIDTH 32
#define FUSE_RESERVED_ODM6_PRI_0 0x22
#define FUSE_RESERVED_ODM6_PRI_0_DATA 31:4
#define FUSE_RESERVED_ODM6_PRI_0_WIDTH 28
#define FUSE_RESERVED_ODM6_PRI_1 0x24
#define FUSE_RESERVED_ODM6_PRI_1_DATA 3:0
#define FUSE_RESERVED_ODM6_PRI_1_WIDTH 4
#define FUSE_RESERVED_ODM6_RED_0 0x23
#define FUSE_RESERVED_ODM6_RED_0_DATA 31:4
#define FUSE_RESERVED_ODM6_RED_0_WIDTH 28
#define FUSE_RESERVED_ODM6_RED_1 0x25
#define FUSE_RESERVED_ODM6_RED_1_DATA 3:0
#define FUSE_RESERVED_ODM6_RED_1_WIDTH 4

#define FUSE_RESERVED_ODM7_WIDTH 32
#define FUSE_RESERVED_ODM7_PRI_0 0x24
#define FUSE_RESERVED_ODM7_PRI_0_DATA 31:4
#define FUSE_RESERVED_ODM7_PRI_0_WIDTH 28
#define FUSE_RESERVED_ODM7_PRI_1 0x26
#define FUSE_RESERVED_ODM7_PRI_1_DATA 3:0
#define FUSE_RESERVED_ODM7_PRI_1_WIDTH 4
#define FUSE_RESERVED_ODM7_RED_0 0x25
#define FUSE_RESERVED_ODM7_RED_0_DATA 31:4
#define FUSE_RESERVED_ODM7_RED_0_WIDTH 28
#define FUSE_RESERVED_ODM7_RED_1 0x27
#define FUSE_RESERVED_ODM7_RED_1_DATA 3:0
#define FUSE_RESERVED_ODM7_RED_1_WIDTH 4

enum {
	SECBOOTDEV_SDMMC,
	SECBOOTDEV_NOR,
	SECBOOTDEV_SPI,
	SECBOOTDEV_NAND,
	SECBOOTDEV_LBANAND,
	SECBOOTDEV_MUXONENAND,
	_SECBOOTDEV_MAX,
	_SECBOOTDEV_U32 = 0x7FFFFFFF
};

#define NSEC_BOOT_DEV (_SECBOOTDEV_MAX - 1)

/* io param sizes */
#define DEVKEY_SZ		sizeof(u32)
#define JTAG_DIS_SZ		sizeof(bool)
#define SBK_DEVKEY_STATUS_SZ	sizeof(bool)
#define ODM_PROD_MODE_SZ	sizeof(bool)
#define SEC_BOOT_DEV_CFG_SZ	sizeof(u16)
#define SEC_BOOT_DEV_SEL_SZ	sizeof(u32)
#define SEC_BOOT_DEV_RAW_SEL_SZ	sizeof(u32)
#define SBK_SZ	SZ_16
#define SKU_SZ	sizeof(32)
#define SPARE_BITS_SZ		sizeof(u32)
#define SW_RSVD_SZ	sizeof(u32)
#define DEV_SEL_STRAPS_SZ		sizeof(u32)
#define ODM_RSVD_SZ		32

/* fuse io parameters */
enum {
	DEVKEY = 1,
	JTAG_DIS,
	SBK_DEVKEY_STATUS,
	/*
	 * Programming the odm production fuse at the same
	 * time as the sbk or dev_key is not allowed as it is not possible to
	 * verify that the sbk or dev_key were programmed correctly.
	 */
	ODM_PROD_MODE,
	SEC_BOOT_DEV_CFG,
	SEC_BOOT_DEV_SEL,
	SBK,
	SKU,
	SPARE_BITS,
	SW_RSVD,
	IGNORE_DEV_SEL_STRAPS,
	SEC_BOOT_DEV_RAW_SEL,
	ODM_RSVD,
	_PARAMS_MAX,
	_PARAMS_U32 = 0x7FFFFFFF
};

#define MAX_IO_PARAMS (_PARAMS_MAX - 1)

struct fuse_data {
	u8 sbk[SBK_SZ];
	u8 devkey[DEVKEY_SZ];
	bool jtag_dis;
	u8 bootdev_sel[SEC_BOOT_DEV_SEL_SZ];
	u8 bootdev_sel_raw[SEC_BOOT_DEV_RAW_SEL_SZ];
	u8 bootdev_cfg[SEC_BOOT_DEV_CFG_SZ];
	u8 sw_rsvd[SW_RSVD_SZ];
	bool odm_prod_mode;
	u8 ignore_devsel_straps[DEV_SEL_STRAPS_SZ];
	u8 odm_rsvd[ODM_RSVD_SZ];
};

/*
 * read the fuse settings
 * @param: io_param_type - param type enum
 * @param: size - read size in bytes
 */
int tegra_fuse_read(u32 io_param_type, void *data, int size);

#define FLAGS_DEVKEY			BIT(0)
#define FLAGS_JTAG_DIS			BIT(1)
#define FLAGS_SBK_DEVKEY_STATUS	BIT(2)
#define FLAGS_ODM_PROD_MODE		BIT(3)
#define FLAGS_SEC_BOOT_DEV_CFG	BIT(4)
#define FLAGS_SEC_BOOT_DEV_SEL	BIT(5)
#define FLAGS_SBK			BIT(6)
#define FLAGS_SKU			BIT(7)
#define FLAGS_SPARE_BITS	BIT(8)
#define FLAGS_SW_RSVD		BIT(9)
#define FLAGS_IGNORE_DEV_SEL_STRAPS	BIT(10)
#define FLAGS_SEC_BOOT_DEV_RAW_SEL	BIT(11)
#define FLAGS_ODMRSVD			BIT(12)

/*
 * Prior to invoking this routine, the caller is responsible for supplying
 * valid fuse programming voltage.
 *
 * @param: pgm_data - entire data to be programmed
 */
int tegra_fuse_program(struct fuse_data *pgm_data, u32 flags);

/* Disables the fuse programming until the next system reset */
void tegra_fuse_program_disable(void);

/* Ensure that fuse programming voltage is removed before using this api */
int tegra_fuse_verify(void);

#endif
